apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: levelup
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: levelup
spec:
  serviceName: "redis-headless"
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379